services:
  db:
    image: mcr.microsoft.com/mssql/server:2025-latest
    container_name: next-task-db
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "${SA_PASSWORD}"
      DB: "${DB}"
      PASSWORD: "${PASSWORD}"
      USER: "${USER}"
    expose:
      - "1433" 
    networks:
      - svc-net
    healthcheck:
      test: [ "CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -U ${USER} -P ${PASSWORD} -C -Q 'SELECT 1'" ]
      interval: 10s
      retries: 10
    volumes:
      - vol:/var/opt/mssql
      - ./db:/db
    command: ["/bin/bash", "./db/init.sh"]

  svc:
    build: ./service
    depends_on:
      db:
        condition: service_healthy
    networks:
      - svc-net
    ports:
      - "8080:${SERVER_PORT}"
    environment:
      SECRET: "${SECRET}"
      SERVER_PORT: "${SERVER_PORT}"
      CONTAINER: "${CONTAINER}"
      DB: "${DB}"
      PASSWORD: "${PASSWORD}"
      USER: "${USER}"
volumes:
  vol: 

networks:
  svc-net:
    driver: bridge