services:
  db:
    image: mcr.microsoft.com/mssql/server:2025-latest
    container_name: sql_server
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "YourStrong@123"
    ports:
      - "1433:1433"
    volumes:
      - nexttask:/var/opt/mssql

  backend:
    build: ./backend
    depends_on:
      - db
    environment:
      DB_HOST: sql_server
      DB_PORT: 1433
      DB_USER: sa
      DB_PASS: YourStrong@123

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  nexttask: