services:
  db:
    image: mcr.microsoft.com/mssql/server:2025-latest
    container_name: next-task-db
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "${SA_PASSWORD}"
    ports:
      - "1433:${DB_PORT}"
    healthcheck:
      test: [ "CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P ${SA_PASSWORD} -C -Q 'SELECT 1'" ]
      interval: 10s
      retries: 10
    volumes:
      - vol:/var/opt/mssql
      - ./db:/db
    command: /bin/bash -c "
      /opt/mssql/bin/sqlservr & 
      sleep 20 && 
      /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P ${SA_PASSWORD} -C -i /db/init.sql &&
      wait"

  # backend:
  #   build: ./backend
  #   depends_on:
  #     - db
  #   environment:
  #     DB_HOST: sql_server
  #     DB_PORT: "${DB_PORT}"
  #     DB_USER: sa
  #     DB_PASS: "${SA_PASSWORD}"


volumes:
  vol: