CREATE FUNCTION FormatedErrorMessage_FUNC() RETURNS VARCHAR(300)
AS 
BEGIN
DECLARE @ERRORPROCEDURE AS VARCHAR(100)		
DECLARE @ERRORMESSAGE	AS VARCHAR(150)		
DECLARE @ERRORLINE		AS VARCHAR(10)		
DECLARE @FINALMESSAGE	AS VARCHAR(300)		

	--Get Error message
	SELECT @ERRORMESSAGE   = ERROR_MESSAGE()			

	--Get Procedure name
	SELECT @ERRORPROCEDURE = ERROR_PROCEDURE()

	--Get Line number
	SELECT @ERRORLINE = ERROR_LINE()

	--Form the final message
	EXEC XP_SPRINTF @FINALMESSAGE OUTPUT, 'ERR - %s - occured in PROCEDURE - %s - at LINE - %s '
										, @ERRORMESSAGE, @ERRORPROCEDURE, @ERRORLINE

	--Return the final message
	RETURN @FINALMESSAGE

END

/* EO Functions */


/* SPs */

